<?php

namespace EnhancedProxy_541efc166f8577e5ebfce132290480d81073446f\__CG__\ByExample\DemoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserRestController__JMSInjector
{
    public static function inject($container) {
        require_once 'D:/Programmes/wamp/www/MultimediaService/app/cache/prod/jms_diextra/proxies/EnhancedProxy_541efc166f8577e5ebfce132290480d81073446f-__CG__-ByExample-DemoBundle-Controller-UserRestController.php';
        $c = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('ByExample\\DemoBundle\\Controller\\UserRestController' => array('putUserAction' => array(0 => 'security.access.method_interceptor'), 'postUsersAction' => array(0 => 'security.access.method_interceptor'), 'getUsersAction' => array(0 => 'security.access.method_interceptor'), 'getUserAction' => array(0 => 'security.access.method_interceptor'), 'deleteUserAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_89ee993b043eaaf73dc8102b7e840e1895cf9b20\__CG__\ByExample\DemoBundle\Controller\UserRestController();
        $instance->__CGInterception__setLoader($c);
        return $instance;
    }
}
