<?php

namespace EnhancedProxy_4828730ea97f44e5d33f42ad46418158bf1ded0f\__CG__\ByExample\DemoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserRoleRestController__JMSInjector
{
    public static function inject($container) {
        require_once 'D:/Programmes/wamp/www/MultimediaService/app/cache/dev/jms_diextra/proxies/EnhancedProxy_4828730ea97f44e5d33f42ad46418158bf1ded0f-__CG__-ByExample-DemoBundle-Controller-UserRoleRestController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('ByExample\\DemoBundle\\Controller\\UserRoleRestController' => array('postRolesAction' => array(0 => 'security.access.method_interceptor'), 'getRolesAction' => array(0 => 'security.access.method_interceptor'), 'deleteRoleAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_643529d3d8060dce82e3d655c4f6a742dc637100\__CG__\ByExample\DemoBundle\Controller\UserRoleRestController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
